name: Welcome/Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1>It's great having your contribution to this Project</h1> Thank you for noticing & notifying us for this issue in OptySys. 🤓<br/>If you would like to keep contributing to open-source, you can check out the other projects by <b>Hitesh Rana</b> <a href='https://github.com/hitesh22rana?tab=repositories&q=&type=source&language=&sort='>here</a><br/> Any questions, let us know. 🤓"
          pr-message: "<h1>It's great having your contribution to this project</h1> Thank you for your first pull request to OptySys. 🤓 <br/> If you would like to keep contributing to open-source, you can check out the other projects by <b>Hitesh Rana</b> <a href='https://github.com/hitesh22rana?tab=repositories&q=&type=source&language=&sort='>here</a><br/> Any questions, let us know. 🤓"
